# Generated by Django 5.2.10 on 2026-01-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_product_delete_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery',
            field=models.CharField(blank=True, max_length=50, verbose_name='Батарея'),
        ),
        migrations.AddField(
            model_name='product',
            name='camera',
            field=models.CharField(blank=True, max_length=100, verbose_name='Камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='cpu',
            field=models.CharField(blank=True, max_length=100, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=50, verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen',
            field=models.CharField(blank=True, max_length=100, verbose_name='Экран'),
        ),
        migrations.AddField(
            model_name='product',
            name='sim',
            field=models.CharField(blank=True, max_length=50, verbose_name='SIM / Сети'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(blank=True, max_length=50, verbose_name='Память'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=50, verbose_name='Гарантия'),
        ),
    ]
